MvCProj#1/Controllers/JobPostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvCProj_1.Data;
using MvCProj_1.Models;
namespace MvCProj_1.Controllers
{
    public class JobPostsController : Controller
    {
        private readonly MvCProj_1Context _context;

        public JobPostsController(MvCProj_1Context context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            //fetch all job posts
            var jobs = _context.JobPosts.ToList();
            ViewBag.testing = "i'm testing this string ";
            return View(jobs);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobPostsModel newJob)
        {
            if (ModelState.IsValid)
            {
                _context.JobPosts.Add(newJob);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(newJob);
        }

        public async Task<IActionResult> Job([FromRoute] int Id)
        {
            var job = await _context.JobPosts.FirstOrDefaultAsync(x => x.Id == Id);
            if (job == null)
                return NotFound();

            return View(job);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var job = await _context.JobPosts.FirstOrDefaultAsync(x => x.Id == id);
            //send the Job model to create view 
            if (job == null)
                return NotFound();

            return View("~/Views/JobPosts/Create.cshtml", job);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(JobPostsModel job)
        {
            if (ModelState.IsValid)
            {
                if (job == null)
                    return BadRequest("job object is null");

                _context.JobPosts.Update(job);
               await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View("Create",job);
        }

        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            try
            {
                var job= await _context.JobPosts.FirstOrDefaultAsync(y => y.Id == id);
                if (job == null)
                    return BadRequest("No Such Job Exists");

                _context.JobPosts.Remove(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return BadRequest("Error in Deleting Job");
            }
        }
    }
}

MvCProj#1/Controllers/UserController.cs
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvCProj_1.Context;
using MvCProj_1.Data;
using MvCProj_1.Helpers;
using MvCProj_1.Models.Authentication;
using System.Data;

namespace MvCProj_1.Controllers
{
    public class UserController : Controller
    {
        private readonly MvCProj_1Context _context;
        public IConfiguration _config;

        private readonly DBContext _dbContext;
        
        public UserController(MvCProj_1Context context,IConfiguration config,DBContext dbContext)
        {
            _context= context;
            _config = config;
            _dbContext= dbContext;
        }
        //[AllowAnonymous]
        [Authorize]
        public async Task<IActionResult> Index(int id)
        {
            var token = HttpContext.Request.Cookies["jwtToken"];

            var foundUser=await _context.Users.FirstOrDefaultAsync(u=>u.Id==id);
            if (foundUser != null)
                return View(foundUser);

            else
                return NotFound();
        }

        [Authorize]
        public async Task<IActionResult> HiddenRoute()
        {
            using (var connection = _dbContext.CreateConnection())
            {
                var data = (await connection.QueryAsync<object>("sp_getEmployeesDetails",
                                                              param: new
                                                              {
                                                                  EmpIdRangeStart = 100,
                                                                  EmpIdRangeEnd = 110
                                                              },
                                                              commandType: CommandType.StoredProcedure));
                if (data!=null)
                    return View();
                ViewData["data"] = data;
                return RedirectToAction("Index","Home");
            }
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] UserRegisterModel userObj)
        {
            if (ModelState.IsValid)
            {
                var user = new UserModel
                {
                    FirstName = userObj.FirstName,
                    LastName = userObj.LastName,
                    Email = userObj.Email,
                    Password = userObj.Password
                };
                _context.Users.Add(user);
                await _context.SaveChangesAsync();
                var token = GenerateToken.GenerateJwtToken(user.FirstName, _config);
                //var token = new GenerateToken().GenerateJwtToken(user.FirstName, _config);
                HttpContext.Response.Cookies.Append("jwtToken", token, new CookieOptions
                {
                    HttpOnly = true,
                    Secure = true, // Ensure this is set in production with HTTPS
                });
                return RedirectToAction(nameof(Index),new { id = user.Id });
            }
            return BadRequest();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]              
        public IActionResult Login([FromForm] UserLoginModel user)
        {
            if (ModelState.IsValid)
            {
                var foundUser=_context.Users.FirstOrDefault(u=>u.Email== user.Email && u.Password==user.Password);
                if (foundUser != null)
                {
                    var token = GenerateToken.GenerateJwtToken(foundUser.FirstName, _config);
                    //var token = new GenerateToken().GenerateJwtToken(user.FirstName, _config);
                    //HttpContext.Response.Cookies.Append("jwtToken", token, new CookieOptions
                    //{
                    //    HttpOnly = true,
                    //    Secure = true, // Ensure this is set in production with HTTPS
                    //});
                    Response.Cookies.Append("jwtToken", token); // Store token in cookie for authorization
                    return RedirectToAction(nameof(Index), new { id = foundUser.Id });
                }
                return NotFound();

            }
            return Unauthorized();
        }


        public IActionResult logout()
        {
            Response.Cookies.Delete("jwtToken");
           return  RedirectToAction("Index","Home");
        }
        public string getToken()
        {
            return GenerateToken.GenerateJwtToken("test", _config);
        }
    }

}
/**/

MvCProj#1/Views/Shared/_Layout.cshtml
@{
    var jwtToken = Context.Request.Cookies["jwtToken"];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvCProj 1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvCProj_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvCProj_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JobPosts" asp-action="Index">JobPosts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                        </li>
                        <!--When there is no login then only display login button-->
                        @if (string.IsNullOrEmpty(jwtToken))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        }

                        <!--Check the cookie present in the session to display logout button-->
                        @if (!string.IsNullOrEmpty(jwtToken))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvCProj_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>